### ISSUE TITLE
Create and upload Debian package

### ISSUE THREAD

**Issue by christophebedard** [colcon/colcon-coveragepy-result#13]
To make `colcon-coveragepy-result` available through the ROS apt repository.

**Comment by christophebedard** [comment]
@dirk-thomas how should I proceed with this?

**Comment by dirk-thomas** [comment]
Let me know which tag should be released and I can go ahead and create / upload the Debian package for it.

**Comment by christophebedard** [comment]
`0.0.7`

Is this how you would like to proceed for future releases/uploads? I don't think new releases will happen that often for this, but if there is any way I can help out with the Deb creation/upload process, let me know.

**Comment by dirk-thomas** [comment]
> 0.0.7

Debian pkg :ship:-ed.

Just a note: the Debian package is available from the master repo right away. The various mirrors will be updated based in different triggers.

> Is this how you would like to proceed for future releases/uploads? I don't think new releases will happen that often for this, but if there is any way I can help out with the Deb creation/upload process, let me know.

The process is pretty simple. I just have to invoke [this little script](https://github.com/ros-infrastructure/ros_release_python). But the upload requires SSH access to the machine which contains the `apt` repo we we can't give to other people atm.

Please feel free to mention me whenever you like a Debian package to be created / uploaded.

**Comment by christophebedard** [comment]
Alright, thank you!
