### ISSUE TITLE
mapping values are not allowed here

### ISSUE THREAD

**Issue by alzeha** [colcon/colcon-coveragepy-result#19]
Hi,

this is my first time, I try to install a mixin and maybe I am the problem, but at least I want to report this:

`$ colcon mixin add coverage-pytest https://github.com/colcon/colcon-coveragepy-result`
`$ colcon mixin update coverage-pytest`

results into

`fetching coverage-pytest: https://github.com/colcon/colcon-coveragepy-result ...`
`    mapping values are not allowed here`
`    in "<unicode string>", line 52, column 50:`
`        ... colcon/colcon-coveragepy-result: A colcon extension for collect ...`

I am not sure, what exactly the problem is. In case this is not the correct way to install this mixin, I would be very happy about an hint (this is maybe also something, that should be done in the README).

Thanks a lot!

**Comment by christophebedard** [comment]
Hi! This isn't exactly a mixin: it's a colcon extension, i.e. a colcon command.

You should be able to install `colcon-coveragepy-result` using `apt` (for debian-based systems) or `pip`, e.g.

```sh
$ sudo apt install python3-colcon-coveragepy-result
```

or

```sh
$ pip3 install colcon-coveragepy-result
```

Once that's done, you should see `coveragepy-result` as an available command when you run `colcon --help`, e.g.

```sh
$ colcon --help
usage: colcon [-h] [--log-base LOG_BASE] [--log-level LOG_LEVEL] {build,coveragepy-result,extension-points,extensions,graph,info,lcov-result,list,metadata,mixin,test,test-result,version-check} ...

...
```

**Comment by christophebedard** [comment]
The mixin mentioned in the README is to allow you to easily enable coverage information generation when building your package & running your code.

I'll add an "install" section to make this a bit clearer.

**Comment by alzeha** [comment]
ah, ok. Sorry, did not get that. Thanks a lot, closing.
